---
title: "GSE37722-GSE192918_EpiDISH"
author: "L"
date: "2023-08-07"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
# Load EpiDISH package, .m file dummy, and the EpiFibIC reference
library(EpiDISH)

if (!requireNamespace("GEOquery", quietly = TRUE))
    BiocManager::install("GEOquery")

if (!requireNamespace("tidyverse", quietly = TRUE))
    BiocManager::install("tidyverse")

library(GEOquery)
library(limma)
library(openxlsx)
library(tidyverse)
library(reshape2)

# Load series and platform data from GEO for GSE37722
gset1 <- getGEO("GSE37722", GSEMatrix = TRUE, getGPL = FALSE)
if (length(gset1) > 1) idx <- grep("GPL8490", attr(gset1, "names")) else idx <- 1
gset1 <- gset1[[idx]]

# Load data from GSE192918
gset2 <- getGEO("GSE192918", GSEMatrix = TRUE, getGPL = FALSE)
if (length(gset2) > 1) idx <- grep("GPL21145", attr(gset2, "names")) else idx <- 1
gset2 <- gset2[[idx]]

# Extract expression matrices from both datasets
ex1 <- exprs(gset1)
ex2 <- exprs(gset2)

# INSERT BMIQ HERE and incorporate the gset1 and 2 - confirmed with str that the matrix of beta values is good for BMIQ input. 
if (!requireNamespace("wateRmelon", quietly = TRUE))
    BiocManager::install("wateRmelon")
if (!requireNamespace("RPMM", quietly = TRUE)) {
    install.packages("RPMM")
}
library(wateRmelon)
library(RPMM)

# AND NOW WE APPLY BMIQ
# Apply BMIQ normalization to ex1_imputed
ex1_bmiq <- BMIQ(ex1_imputed, design.v = NULL, nL = 3, doH = TRUE, nfit = 1000, th1.v = c(0.2, 0.75), th2.v = NULL, niter = 5, tol = 0.001, plots = TRUE, sampleID = 1, pri = TRUE)

#Sam playing around
ex1_bmiq <- BMIQ(test, design.v = NULL, nL = 3, doH = TRUE, nfit = 1000, th1.v = c(0.2, 0.75), th2.v = NULL, niter = 5, tol = 0.001, plots = FALSE, sampleID = colnames(test), pri = TRUE)

# Apply BMIQ normalization to ex2_imputed
ex2_bmiq <- BMIQ(ex2_imputed, design.v = NULL, nL = 3, doH = TRUE, nfit = 50000, th1.v = c(0.2, 0.75), th2.v = NULL, niter = 5, tol = 0.001, plots = TRUE, sampleID = 1, pri = TRUE)


# Create a sample data frame with matched IDs for GSE37722
matched_ids_GSE37722 <- data.frame(
  GSM_lines = c("GSM926075", "GSM926079", "GSM926083", "GSM926087", "GSM926091", "GSM926095", "GSM926099", "GSM926103", "GSM926107", "GSM926111", "GSM926115", "GSM926119", "GSM926123", "GSM926127", "GSM926129", "GSM926130", "GSM926131", "GSM926132", "GSM926133", "GSM926134", "GSM926135", "GSM926136", "GSM926137", "GSM926138", "GSM926139", "GSM926140", "GSM926141", "GSM926142"),
  Pregnancy_Status = c("NL-0008-del", "NL-0028-del", "NL-0030-del", "NL-0031-del", "NL-0043-del", "NL-0045-del", "NL-0070-del", "NL-0080-del", "NL-0105-del", "NL-0122-del", "NL-0128-del", "NL-0152-del", "NL-0158-del", "NL-0215-del", "PE-0001-del", "PE-0007-del", "PE-0008-del", "PE-0012-del", "PE-0028-del", "PE-0034-del", "PE-0046-del", "PE-0060-del", "PE-0064-del", "PE-0065-del", "PE-0066-del", "PE-0069-del", "PE-0073-del", "PE-0074-del")
)

# Filter matched_ids_GSE37722 to include only NL samples
matched_ids_GSE37722_NL <- matched_ids_GSE37722 %>%
  filter(grepl("^NL-", Pregnancy_Status))

# Extract corresponding sample IDs from matched_ids_GSE37722_NL
matched_sampleIDs_GSE37722_NL <- matched_ids_GSE37722_NL$GSM_lines

# Filter matched_ids_GSE37722 to include only PE samples
matched_ids_GSE37722_PE <- matched_ids_GSE37722 %>%
  filter(grepl("^PE-", Pregnancy_Status))

# Extract corresponding sample IDs from matched_ids_GSE37722_PE
matched_sampleIDs_GSE37722_PE <- matched_ids_GSE37722_PE$GSM_lines

# Combine the selected sample IDs from GSE192918 and GSE37722
combined_sampleIDs <- c(matched_sampleIDs_GSE37722_NL, "GSM5769034", "GSM5769038", "GSM5769042", "GSM5769046", "GSM5769050", "GSM5769054", "GSM5769058", "GSM5769062", "GSM5769066", "GSM5769070")

# Assuming ex1_combined and ex2_common are your expression matrices
# Create data frames for each matrix
df_ex1 <- as.data.frame(ex1_bmiq)
df_ex1$probeID <- rownames(df_ex1)

df_ex2 <- as.data.frame(ex2_bmiq)
df_ex2$probeID <- rownames(df_ex2)
# Add sample ID columns to each data frame
#df_ex1$SampleID <- rownames(df_ex1)
#df_ex2$SampleID <- rownames(df_ex2)

# Combine data frames by SampleID
combined_df <- merge(df_ex1, df_ex2, by = "probeID")
#combined_df$SampleID <- as.factor(combined_df$SampleID)

#replace all NA with 0
combined_df[is.na(combined_df)] <- 0
rownames(combined_df) <- combined_df$probeID
combined_df$probeID <- NULL

# Run EpiDISH analysis on the merged data
merged_out <- epidish(beta.m = combined_df, ref.m = centEpiFibIC.m, method = "RPC")
merged_estF <- merged_out$estF

##estF is matrix of estimated cell-type fractions; ref is centroi matrix and dataREF is a subset of the input data matrix over the probes defined in the ref matrix
merged_out$estF
dim(merged_out$ref)
dim(merged_out$dataREF)

data(merged_out)
BloodFracMerged.m <- epidish(beta.m = combined_df, ref.m = centDHSbloodDMC.m, method = "RPC")$estF

# Print the estimated cell-type fractions
print(merged_estF)
print(BloodFracMerged.m)

#SO AT THIS POINT, THE BloodFracMerged.m has all of the samples from BOTH sample sets. So I want to subset it to only the sample that I want to analyze and label them as CONTROL and PE.
# List of selected GSMs
selected_GSMs <- c(
    "GSM926075", "GSM926079", "GSM926083", "GSM926087", "GSM926091", "GSM926095",
    "GSM926099", "GSM926103", "GSM926107", "GSM926111", "GSM926115", "GSM926119",
    "GSM926123", "GSM926127", "GSM5769034", "GSM5769038", "GSM5769042", "GSM5769046",
    "GSM5769050", "GSM5769054", "GSM5769058", "GSM5769062", "GSM5769066", "GSM5769070",
    "GSM926129", "GSM926130", "GSM926131", "GSM926132", "GSM926133", "GSM926134",
    "GSM926135", "GSM926136", "GSM926137", "GSM926138", "GSM926139", "GSM926140",
    "GSM926141", "GSM926142"
)

# Subsetting the data frame
subsetCtlPE_data <- BloodFracMerged.m[selected_GSMs, ]

# Printing the subsetted data frame
print(subsetCtlPE_data)

# Save the subsetCtlPE_data table as a text file
write.table(subsetCtlPE_data, file = "BloodFrac.Ctl.PE-11August2023.txt", sep = "\t", quote = FALSE, row.names = TRUE)

library(ggplot2)
library(reshape2)

# Read data from the text file
data_path <- "/Users/laibajamshed/Library/CloudStorage/OneDrive-McMasterUniversity/Wilson_Pregnancy_Lab_Docs/Lab_notebooks/Jamshed_Laiba_Lab_Notebook/GSE3772_IncreasedControls/BloodFrac.Ctl.PE-11August2023.txt"
subsetCtlPE_data <- read.table(data_path, header = TRUE, row.names = 1)

# Create a "Group" column based on row number
subsetCtlPE_data$Group <- ifelse(rownames(subsetCtlPE_data) %in% rownames(subsetCtlPE_data)[1:24], "Normotensive", "Preeclampsia")

# Melt the data for box plots
melted_data <- melt(subsetCtlPE_data, id.vars = c("Group"), variable.name = "Cell_Type")

# Filter data for each cell type and create separate plots
plots <- lapply(levels(melted_data$Cell_Type), function(cell_type) {
  subset_data <- subset(melted_data, Cell_Type == cell_type)
  p <- ggplot(subset_data, aes(x = Group, y = value, fill = Group)) +
    geom_boxplot() +
    labs(x = NULL, y = "Estimated Cell Fraction") +
    scale_fill_manual(values = c("Normotensive" = "black", "Preeclampsia" = "white")) +
    theme_bw() +
    theme(panel.background = element_rect(fill = "white"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_rect(fill = "white"),
          strip.text = element_text(color = "black"),
          legend.position = "none",  # Keep legend on for one plot
          axis.text.x = element_blank(),
          axis.title.y = element_text(size = 9),
          axis.text.y = element_text(size = 10),
          axis.ticks.y = element_line(size = 0.5),
          plot.margin = margin(0.5, 0.5, 0.5, 0.5),
          plot.title = element_text(size = 9, hjust = 0.5),
          aspect.ratio = 1) +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01))  # Set decimal places
  
  # Add cell type title at the top
  p <- p + ggtitle(cell_type)
  
  return(p)
})


# Create a legend grob from one of the plots
legend_grob <- cowplot::get_legend(plots[[1]])

# Combine the plots and legend using cowplot
grid_arrange <- cowplot::plot_grid(plotlist = plots, ncol = 3)
final_plot <- cowplot::plot_grid(grid_arrange, legend_grob, ncol = 2, rel_widths = c(8, 2))

# Display the final combined plot
print(final_plot)
```

```{r}
##GRAPHING ONLY
library(ggplot2)
library(reshape2)
library(cowplot)

# Read data from the text file
data_path <- "/Users/laibajamshed/Library/CloudStorage/OneDrive-McMasterUniversity/Wilson_Pregnancy_Lab_Docs/Lab_notebooks/Jamshed_Laiba_Lab_Notebook/GSE3772_IncreasedControls/BloodFrac.Ctl.PE-11August2023.txt"
subsetCtlPE_data <- read.table(data_path, header = TRUE, row.names = 1)

# Create a "Group" column based on row number
subsetCtlPE_data$Group <- ifelse(rownames(subsetCtlPE_data) %in% rownames(subsetCtlPE_data)[1:24], "Normotensive", "Preeclampsia")

# Melt the data for box plots
melted_data <- melt(subsetCtlPE_data, id.vars = c("Group"), variable.name = "Cell_Type")

# Filter data for each cell type and create separate plots
plots <- lapply(levels(melted_data$Cell_Type), function(cell_type) {
  subset_data <- subset(melted_data, Cell_Type == cell_type)
  p <- ggplot(subsetCtlPE_data, aes(x = Group, y = value, fill = Group)) +
    geom_boxplot() +
    labs(x = NULL, y = "Estimated Cell Fraction") +
    scale_fill_manual(values = c("Normotensive" = "black", "Preeclampsia" = "white")) +
    theme_bw() +
    theme(panel.background = element_rect(fill = "white"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_rect(fill = "white"),
          strip.text = element_text(color = "black"),
          legend.position = "none",  # Keep legend on for one plot
          axis.text.x = element_blank(),
          axis.title.y = element_text(size = 9),
          axis.text.y = element_text(size = 10),
          axis.ticks.y = element_line(size = 0.5),
          plot.margin = margin(0.5, 0.5, 0.5, 0.5),
          plot.title = element_text(size = 9, hjust = 0.5),
          aspect.ratio = 1) +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01))  # Set decimal places
  
  # Add cell type title at the top
  p <- p + ggtitle(cell_type)
  
  return(p)
})

# Create a legend grob from one of the plots
legend_grob <- cowplot::get_legend(plots[[1]])

# Combine the plots and legend using cowplot
grid_arrange <- cowplot::plot_grid(plotlist = plots, ncol = 3)
final_plot <- cowplot::plot_grid(grid_arrange, legend_grob, ncol = 2, rel_widths = c(8, 2))

# Display the final combined plot
print(final_plot)
```

```{r}
# List of cell types
cell_types <- unique(melted_data$Cell_Type)

# Create an empty data frame to store t-test results
t_test_results <- data.frame(Cell_Type = character(0), p_value = numeric(0))

# Loop through each cell type and perform t-test
for (cell_type in cell_types) {
  subsetCtlPE_data <- subset(melted_data, Cell_Type == cell_type)
  t_test_result <- t.test(value ~ Group, data = subsetCtlPE_data)
  t_test_results <- rbind(t_test_results, data.frame(Cell_Type = cell_type, p_value = t_test_result$p.value))
}

# Print t-test results
print(t_test_results)

```


```{r}
# Create an empty data frame to store t-test results
t_test_results <- data.frame(Cell_Type = character(0), p_value = numeric(0))

# Loop through each cell type and perform t-test
for (cell_type in cell_types) {
  subsetCtlPE_data <- subset(melted_data, Cell_Type == cell_type)
  t_test_result <- t.test(value ~ Group, data = subsetCtlPE_data)
  t_test_results <- rbind(t_test_results, data.frame(Cell_Type = cell_type, p_value = t_test_result$p.value))
}

# Create a data frame with the asterisk positions and significance levels
asterisk_data <- p_value_data %>%
  mutate(significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Merge the p-value and asterisk data with the original data frame
melted_data_with_asterisks <- merge(melted_data, asterisk_data, by = "Cell_Type")

# Create the multi-panel figure with asterisks
p_with_asterisks <- p +
  geom_text(data = melted_data_with_asterisks,
            aes(x = Group, label = significance, y = Inf),
            color = "black",
            hjust = -1.95,
            vjust = 1.5,
            inherit.aes = FALSE)

# Display the graph with asterisks
print(p_with_asterisks)


```


